name: Generate Ascii Artwork
on: [push]

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y

      - name: Execute Cowsay Command
        run: cowsay -f dragon "Run for cover, I am dragon....RWR" > dragon.txt

      - name: Sleep For 30 Seconds
        run: sleep 30

      - name: Upload dragon.txt as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dragon-artifact
          path: dragon.txt

  test_job_2:
    runs-on: ubuntu-latest
    needs: build_job_1
    steps:
      - name: Download dragon.txt
        uses: actions/download-artifact@v4
        with:
          name: dragon-artifact

      - name: Sleep for 30 Seconds
        run: sleep 30

      - name: Test Files Exists
        run: grep -i "dragon" dragon.txt

  deploy_job_3:
    runs-on: ubuntu-latest
    needs: build_job_1
    steps:
      - name: Download dragon.txt
        uses: actions/download-artifact@v4
        with:
          name: dragon-artifact

      - name: Test File Exists
        run: grep -i "dragon" dragon.txt

      - name: Read the File
        run: cat dragon.txt

      - name: List Files (Verify Output)
        run: ls -ltr