name: Generate Ascii Artwork
on: [push]  # Triggers on any push event

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y  # Use lowercase "cowsay"

      - name: Execute Cowsay Command
        run: cowsay -f dragon "Run for cover, I am dragon....RWR" > dragon.txt  # Fix command case
      - name: Sleep For 30 Second
        run: sleep 30 Second
  Test_job_2:
     runs-on: ubuntu-latest
  steps:
     - name: sleep for 30 Second
       run: sleep 30 Second
     - name: Test Files Exists
       run: grep -i "dragon" dragon.txt
  Deploy_job_3:

      - name: Test File Exists
        run: grep -i "dragon" dragon.txt  # Verify content

      - name: Read the File
        run: cat dragon.txt  # Proper indentation

      - name: List Files (Verify Output)
        run: ls -la  # Check if dragon.txt exists